# Project information
site_name: Ortal NoteBooks
# defeine TOC or order of website-
nav:
  - HOME: topics.md
  - MKDOCS: mkdocs.md
  - TypeScript: typescript.md

site_author: Ortal Sabag
site_description: >-
  DESCRIPTION

# Repository
repo_name: ortalaharon/ortal_mkdocs

repo_url: https://github.com/ortalaharon/ortal_mkdocs

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #090909
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ortalaharon
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ortal-aharon-sabag-b599085b/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/ortalaharon"  target="_blank" rel="noopener">Ortal Aharon Sabag</a>
